using AF_mobile_web_api.Domain;
using AF_mobile_web_api.DTO;
using ApplicationDatabase.Models;
using AutoMapper;

namespace AF_mobile_web_api.Mappings
{
    public class MappingProfile: Profile
    {
        public MappingProfile()
        {
            CreateMap<SearchDataDTO, SearchData>()
                .ForMember(dest => dest.Location, opt => opt.Ignore());

            CreateMap<SearchData, SearchDataDTO>();

            CreateMap<SearchData, PropertyData>()
                .ForMember(x => x.Id, opt => opt.Ignore()) // surrogate PK generated by the database
                .ForMember(x => x.City, opt => opt.MapFrom(src => src.Location.City))
                .ForMember(x => x.District, opt => opt.MapFrom(src => src.Location.District))
                .ForMember(x => x.Lat, opt => opt.MapFrom(src => src.Location.Lat))
                .ForMember(x => x.Lon, opt => opt.MapFrom(src => src.Location.Lon))
                .ForMember(x => x.WebName, opt => opt.MapFrom(src => (int)src.WebName))
                .ForMember(x => x.AddedRecordTime, opt => opt.Ignore()); // set once per scrape batch in the write path

            // Reverse map: reconstruct the SearchData shape the dashboard aggregation expects
            // from a flat PropertyData row.
            CreateMap<PropertyData, SearchData>()
                .ForMember(x => x.Id, opt => opt.MapFrom(src => src.Id.ToString()))
                .ForMember(x => x.WebName, opt => opt.MapFrom(src => (WebName)src.WebName))
                .ForMember(x => x.Location, opt => opt.MapFrom(src => new LocationPlace
                {
                    City = src.City,
                    District = src.District,
                    Lat = src.Lat,
                    Lon = src.Lon
                }));
        }
    }
}
